remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: SOFT-AIS
description: Residual Stress Analysis Software
show_downloads: true
github:
  zip_url: http://example.com/download.zip
