remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: SOFT-AIS
description: Residual Stress Analysis Software
show_downloads: true
github:
zip_url: Windows_Installer/.gitignore

related_resources_title: Other Resources

related_resources_list:

- title: Forums
  hurl: https://some.developer.forum.com/

- title: More Documentation
  hurl: https://more.documentation.company.com

- title: Documentation Portal
  hurl: https://my.documentation.portal
